- include_tasks: disks.yaml
  tags: disks
- include_tasks: users.yaml
  tags: users
- include_tasks: apt.yaml
  tags: apt
- include_tasks: prime_server.yaml
  tags: prime_server
- include_tasks: valhalla.yaml
  tags: valhalla
